file_format: "1"
id: cck-ball
name: CCK-BALL
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - cck-ball_left
  - cck-ball_right
